name: Test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/test.yml'

jobs:
  print-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Check out pull request
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4

      - name: Check out branch
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      
      - name: Print GitHub Secret
        env:
          MY_SECRET: ${{ secrets.test_secret }}
        run: |
          echo "Printing a GitHub Secret for testing purposes:"
          echo "Secret value: $MY_SECRET"